const express = require('express');
const router = express.Router();
const friendController = require('../controllers/friendController');
const authMiddleware = require('../middlewares/authMiddleware'); 
router.post('/friends/send', authMiddleware, friendController.send);
router.post('/friends/accept', authMiddleware, friendController.accept);
router.post('/friends/reject', authMiddleware, friendController.reject);
router.get('/friends/all', authMiddleware, friendController.getAllData);
router.delete('/friends/cancel/:receiverId', authMiddleware, friendController.cancel);
router.delete('/friends/unfriend/:friendId', authMiddleware, friendController.unfriend);
router.post('/friends/create-chat', authMiddleware, friendController.createChat);
module.exports = router;